### ISSUE TITLE
Kapitel 2 Folien Review

### ISSUE THREAD

**Issue by wangfelix** [eduref/python-for-beginners#25]
<img width="204" alt="image" src="https://github.com/eduref/python-for-beginners/assets/57860405/79e31e35-ccd4-4a19-9710-7956f96cc987"

- Ich glaube diese Folien sollen nicht Teil des Folgesatzes sein.

<img width="815" alt="image" src="https://github.com/eduref/python-for-beginners/assets/57860405/08d41be6-b305-4983-ac62-401b00e33ebf">

- Hier fehlt noch der Verweis

<img width="631" alt="image" src="https://github.com/eduref/python-for-beginners/assets/57860405/9cec54fa-6259-42b3-bb69-164d19ae2f49">

- Hier sollte "Introduction to IDEs and Jupyter Notebooks" stehen.

**Comment by karltlf** [comment]
gefixt & hochgeladen
