### ISSUE TITLE
Kapitel 01 Folien Review

### ISSUE THREAD

**Issue by wangfelix** [eduref/python-for-beginners#26]
<img width="768" alt="image" src="https://github.com/eduref/python-for-beginners/assets/57860405/a14816aa-18df-4adb-98d6-b561845d770e">

- Bei 2. sollte "Introduction to IDEs and Jupyter Notebook" stehen
- Bei 3. sollte "The print function and String concatenation"
- Haben wir Kapitel 13 "Packages oder Spiele" gestrichen?

**Comment by karltlf** [comment]
String concatenation wird bei 3. nicht gemacht, passe ich gleich in der readme an @wangfelix

**Comment by karltlf** [comment]
Hab folien reviewt, angepasst & hochgeladen
