### ISSUE TITLE
[SLIDE REVIEW] Chapter 06 - arithmetic operations

### ISSUE THREAD

**Issue by karltlf** [eduref/python-for-beginners#29]
<h2>Code screenshots für die Beispiele?</h2>
<img width="1039" alt="Bildschirmfoto 2024-01-19 um 13 34 21" src="https://github.com/eduref/python-for-beginners/assets/68251820/8af3c976-c756-409b-b491-58b67fcd510f">
<h2>Same here</h2>
<img width="1047" alt="grafik" src="https://github.com/eduref/python-for-beginners/assets/68251820/51e92152-df66-444e-9b67-bc4b221d0d3b">

**Comment by vinzenzzinecker98** [comment]
erledigt
