### ISSUE TITLE
[SLIDE REVIEW] chapter 05 - input

### ISSUE THREAD

**Issue by karltlf** [eduref/python-for-beginners#30]
<h2>What do you mean here?</h2>
 int() converts string to int but int() does not accept strings is what it sounds like
<img width="994" alt="grafik" src="https://github.com/eduref/python-for-beginners/assets/68251820/fe4bc6ab-1e1b-4ef1-8ee6-f0efe73ae710">

**Comment by vinzenzzinecker98** [comment]
habe das besser formuliert
