### ISSUE TITLE
chapter 7 review

### ISSUE THREAD

**Issue by WeiiswurstDev** [eduref/python-for-beginners#31]
Code:
- Exercise 2: Vlt. noch einen Hinweis dazumachen, dass man booleans mit str() zu Strings machen kann. Eigentlich sollte das denen schon klar sein, aber sicher ist sicher.
- Exercise 4: Es würde mich sehr sehr wundern, wenn einer der Teilnehmer die mathematische Schreibweise für bool'sche Ausdrücke kennt. Aber es schadet auch nicht, sie da zu lassen.

Die Codeblocks haben alle Solution Marker ("write your code after this line") am richtigen Ort 👍

Folien:
- Ganz am Anfang wäre es vlt. gut, sehr explizit zu sagen, dass booleans entweder True oder False sein können.
- Die Folien haben Lösungen. Meines Wissens nach wollten wir eigentlich keine Lösungen auf Folien, weil die Lösungen ja auch im Repo sind und wenn man auf den Folien Lösungen hat, man dann auch zwei Sets von Folien braucht (1x mit Lösungen und 1x Ohne).
- Slide 8: "corresponds to binary number 1" bzw "0": 0 und 1 sind zwar auch Binärzahlen, aber was genau das überhaupt heißt kommt im Kurs nicht dran. Daher wäre "corresponds to number 1" oder "number 0" besser, weil es auch stimmt und weil die Teilnehmer vermutlich nicht wissen was eine Binärzahl ist.

**Comment by karltlf** [comment]
@WeiiswurstDev Lösungen auf Folien werden wir machen, weil es sinnvoll ist, aufm beamer nicht zwischen notebook und folien switchen zu müssen. Also werden wir einf screenshots der lösungen in die folien packen

**Comment by karltlf** [comment]
Code fertig reviewt.
@wangfelix für die Folien zuständig

**Comment by wangfelix** [comment]
closed
