### ISSUE TITLE
[SLIDE REVIEW] Chapter 4 datatypes-variables

### ISSUE THREAD

**Issue by vinzenzzinecker98** [eduref/python-for-beginners#39]
- habe die ganzen placeholder folien mal rausgelöscht

An sich alles gut, was noch komplett fehlt sind die Lösungen zu den Aufgaben auf den slides

Und auch die Aufgabenstellungen würde ich vollständig auf die Folien machen, sonst ist man als Kurshalter lost weil man nicht die Aufgabe erklären kann ohne bei den Teilnehmern die Aufgabe zu suchen und nachzulesen

Was cool ist: Die ganzen Container

**Comment by vinzenzzinecker98** [comment]
QR Code habe ich schon eingefügt

**Comment by karltlf** [comment]
Yo Aufgabenstellung + Lösung muss ich noch reinpacken.
Außerdem habe ich die Casts vergessen - müssenda noch die str(),float(),int() Methoden zu den Folien hinzufügen
