### ISSUE TITLE
Chapter 5 Lösungsfolien fehlen

### ISSUE THREAD

**Issue by wangfelix** [eduref/python-for-beginners#49]
Lösungsfolien zu Exercise 1 und 2 fehlen

**Comment by karltlf** [comment]
@wangfelix hattest du das noch gemacht?

**Comment by wangfelix** [comment]
@karltlf Ne ich hab den Task für Vinzenz angelegt. Er wollte das noch machen.

**Comment by vinzenzzinecker98** [comment]
done
