### ISSUE TITLE
Fix slides for 07 booleans

### ISSUE THREAD

**Issue by WeiiswurstDev** [eduref/python-for-beginners#54]
- [x] Wir brauchen eine Folie, wo erklärt wird, wie man von menschlicher Sprache (Es ist wahr, wenn a oder b wahr sind und c wahr ist) zu code kommt.
- [x] Lösung der Aufgabe 4 ist falsch auf den Folien
- [ ] Mathematische Schreibweise bei Nr 4 korrigieren 
- [x] Auf einigen Folien sind ?? statt Pfeilen, zumindest in meinem powerpoint.

**Comment by Yannickueuev** [comment]
Notebook chapter 07 muss noch korrigiert (Änderung hochladen) werden, ich versteh das mit dem bearbeiten / Branchen nicht so ganz, machen wir beim nächsten Treffen kurz
