### ISSUE TITLE
Workflow Aufgaben bearbeiten?

### ISSUE THREAD

**Issue by karltlf** [eduref/python-for-beginners#61]
@WeiiswurstDev Für welchen Branch soll ich PRs erstellen? Meine bearbeiteten aufgaben haben ja lösungen, also sollten sie ja eigentlich in den `solutions` branch gemerget werden.
Hattet ihr hierfür einen Workflow?

Habe jetzt aber gesehen, dass neue/bearbeitete Aufgaben direkt in main gemerget werden, wo ja eigentlich nur aufgaben ohne lösungen stehen sollen

**Comment by WeiiswurstDev** [comment]
Wir haben vor allem Bonusaufgaben in main hinzugefügt, die sowieso keine Lösungen haben müssen (sie werden ja nicht besprochen). Irgendwann, am besten nachdem die jetzigen Probleme behoben sind, müssen wir solutions um die Aufgaben und ggf Lösungen aus main ergänzen und andersrum. Wir können uns auch mal zusammensetzen und eine bessere Lösung finden, ich habe jetzt erstmal nur den Status Quo beschrieben.

**Comment by karltlf** [comment]
Main ist zwar schon protected aber vllt können wir es so einstellen, dass man gar keine PRs für main aufmachen darf sondern stattdessen nur solutions erlaubt. Nur für die Zukunft
